### ISSUE TITLE
KeyError: 'cs'

### ISSUE THREAD

**Issue by jomit** [Azure-Samples/azure-iot-starterkit-cli#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
iot --wifi-ssid TEXT --wifi-password TEXT --resource-group TEXT --iothub TEXT configure-device

### Any log messages given by the failure
>
Checking for Connection String for device with name 'grovevisionkit'
Traceback (most recent call last):
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jovagh\AppData\Local\Programs\Python\Python36\Scripts\iot.exe\__main__.py", line 9, in <module>
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\site-packages\iot.py", line 411, in cli
    set_missing_parameters(ctx.obj)
  File "c:\users\jovagh\appdata\local\programs\python\python36\lib\site-packages\iot.py", line 132, in set_missing_parameters
    iot.set_config("cs", device_info["cs"])
KeyError: 'cs'

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
> Enterprise

### Mention any other details that might be useful

> ---------------------------------------------------------------

**Comment by maeg02** [comment]
Is this issue fix, because we experience the same thing

**Comment by fredplain** [comment]
Hello guys, have the exact same error message, has anyone fixed it? Thanks

**Comment by maeg02** [comment]
> Hello guys, have the exact same error message, has anyone fixed it? Thanks

You can look at #11  and apply that fix, it worked for me...

**Comment by fredplain** [comment]
Thanks Markus, it worked indeed. Thanks

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by good-faith** [comment]
Although it fixed the "cs" error, it seems to hang [here](https://github.com/Azure-Samples/azure-iot-starterkit-cli/blob/e84a803675d8d8bfd4482b8ad520423707a81c13/iot.py#L467) connecting to Raspberry Pi while it's running `configure_device`. 

Can manually configure the pi with the script it downloaded though. 

There is a lot you have to do, but confirm it works,
```
[IoTHubMonitor] There is a running job to monitor built-in event endpoint. Please stop it first.
[IoTHubMonitor] [9:27:04 AM] Message received from [myPi001/temperature-sensor]:
{
  "id": {
    "int": 5.425558052079015e+37
  },
  "ambient": {
    "humidity": 33.90815243573406,
    "temperature": 24.367492648609915
  },
  "timeCreated": "2020-01-24 15:27:04.170048",
  "machine": {
    "pressure": 991.9770315576565,
    "temperature": 24.367492648609915
  }
}
[IoTHubMonitor] [9:27:09 AM] Message received from [myPi001/temperature-sensor]:
{
  "id": {
    "int": 2.9462650776781823e+38
  },
  "ambient": {
    "humidity": 33.86321050241451,
    "temperature": 24.35745106646791
  },
  "timeCreated": "2020-01-24 15:27:09.194481",
  "machine": {
    "pressure": 991.9609122296947,
    "temperature": 24.35745106646791
  }
}
[IoTHubMonitor] [9:27:14 AM] Message received from [myPi001/temperature-sensor]:
{
  "id": {
    "int": 1.5372050497589222e+38
  },
  "ambient": {
    "humidity": 33.93093421506564,
    "temperature": 24.34740948549006
  },
  "timeCreated": "2020-01-24 15:27:14.218744",
  "machine": {
    "pressure": 991.9994299364828,
    "temperature": 24.34740948549006
  }
}
[IoTHubMonitor] Stopping built-in event endpoint monitoring...
[IoTHubMonitor] Built-in event endpoint monitoring stopped.
```
