### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by terrymandin** [Azure-Samples/azure-iot-starterkit-cli#4]
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
pip install azure-iot-starterkit-cli
iot

### Any log messages given by the failure
C:\>iot
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\iot.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\iot.py", line 7, in <module>
    import urllib.request
ImportError: No module named request

### Expected/desired behavior
IoT CLI to start

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful
I tried:

  easy_install.exe requests

as per this url: https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

Sorry, not a Python guy (yet) or I would debug/fix it.

**Comment by terrymandin** [comment]
Appears to only be an issue in Python 2.  It works in Python 3.
